[package]
name = "tarzan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
filetime.workspace = true
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tracing.workspace = true
zstd.workspace = true

[dev-dependencies]
tar.workspace = true
tempfile.workspace = true
zstd.workspace = true
